OTC-279: Return duplicated payment code instead of saving them in db
openimis/rest_api_c-sharp pull request #73
Opened 2021-06-09 09:40 UTC by sniedzielski

TICKET: https://openimis.atlassian.net/browse/OTC-279

2021-06-09 11:02 UTC, sniedzielski commented
@dragos-dobre That is my proposition to support duplicate error with saving this message error into original payment in "RejectedReason" and returning to GePG 7207. I marked this PR as draft because we've been waiting for Juma response about this case. 

As the next step I can implement supporting this issue: "bill id not existing (create the payment with the billid to save the error: -3 if on getCN, -4 if on GetPayment, -5 if on getRecon)" (point from description of OTC-279)

2021-06-09 16:06 UTC, dragos-dobre requested changes

2021-06-09 16:06 UTC, dragos-dobre commented on OpenImis.ePayment/Escape/Payment/Controllers/PaymentController.cs
>                      GepgFileLogger.Log(billId, "Payment", reconc, env);
_response is null so difficult to understand what we save here.

2021-06-09 16:06 UTC, dragos-dobre commented on OpenImis.ePayment/Logic/PaymentLogic.cs
> +                        rejectedReason = payment.PrepareRejectedReason(payment.PaymentId, GepgCodeResponses.GepgResponseCodes["Bill does not exist"].ToString());
We cannot use GepgCodeResponses here as this is part of the generic implementation. The error message must be handled in the escape part, either in PaymentController or ImisPayment in the code between `#if CHF` and `#endif` as only this part is specific for TZ.

2022-03-15 11:25 UTC, delcroip commented
@dragos-dobre , @sniedzielski  Can I close this PR ?

2022-06-01 11:52 UTC, closed without merging